version: "2"
services:
  nginx:
    build: ./nginx/
    ports:
      - "8000:80"
    networks:
      - public-subnet
    depends_on:
      - api
      - front
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./db/volume:/var/lib/mysql
    networks:
      - private-subnet
  api:
    build: ./server/
    networks:
      - public-subnet
      - private-subnet
    depends_on:
      - mysql
  front:
    build: ./front/
    volumes:
      - ./front/src/bff/:/var/www/bff
    networks:
      - public-subnet
networks:
  public-subnet: {}
  private-subnet: {}
