version: "2"
services:
  nginx:
    build: ./nginx/
    ports:
      - "8000:80"
    networks:
      - public-subnet
  api:
    build: ./server/
    ports:
      - "8080:8080"
    networks:
      - public-subnet
  front:
    build: ./front/
    ports:
      - "3000:3000"
    volumes:
      - ./front/src/bff/:/var/www/bff
    networks:
      - public-subnet
networks:
  public-subnet: {}
  private-subnet: {}
