apply/api:
	kubectl apply -f api.yaml

apply/front:
	kubectl apply -f front.yaml

apply/ingress:
	kubectl apply -f ingress.yaml

apply/mysql:
	kubectl apply -f mysql.yaml

pods:
	kubectl get pods

dep:
	kubectl get deployment

service:
	kubectl get service